#!/bin/bash
if [ -z "$PYFILE" ]
	then
		echo "PYFILE is not set"
		exit 1
fi
if [ ! -f "$PYFILE" ]
	then
		echo "Error: Python file '$PYFILE' not found."
		exit 1
fi
echo "Compiling $PYFILE ..."
python3 -m compileall -b "$PYFILE"
